// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: club_join_requests.sql

package db_queries

import (
	"context"
)

const updateClubJoinRequestStatus = `-- name: UpdateClubJoinRequestStatus :one
UPDATE club_join_requests
SET
    status = $1,
    updated_at = now()
WHERE id = $2 and is_deleted = FALSE
RETURNING club_join_requests.id, club_join_requests.club_id, club_join_requests.user_id, club_join_requests.status, club_join_requests.created_at, club_join_requests.updated_at, club_join_requests.is_deleted
`

type UpdateClubJoinRequestStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) UpdateClubJoinRequestStatus(ctx context.Context, arg UpdateClubJoinRequestStatusParams) (ClubJoinRequest, error) {
	row := q.db.QueryRow(ctx, updateClubJoinRequestStatus, arg.Status, arg.ID)
	var i ClubJoinRequest
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}
