// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: club_join_requests.sql

package db_queries

import (
	"context"
	"time"
)

const createJoinRequest = `-- name: CreateJoinRequest :one
INSERT INTO club_join_requests 
(club_id, user_id, status, created_at, updated_at)
VALUES 
($1, $2, $3, $4, $5)
RETURNING id, club_id, user_id, status, created_at, updated_at, is_deleted
`

type CreateJoinRequestParams struct {
	ClubID    int64
	UserID    int64
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateJoinRequest(ctx context.Context, arg CreateJoinRequestParams) (ClubJoinRequest, error) {
	row := q.db.QueryRow(ctx, createJoinRequest,
		arg.ClubID,
		arg.UserID,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ClubJoinRequest
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getAllJoinRequests = `-- name: GetAllJoinRequests :many
SELECT id, club_id, user_id, status, created_at, updated_at, is_deleted
FROM club_join_requests
`

func (q *Queries) GetAllJoinRequests(ctx context.Context) ([]ClubJoinRequest, error) {
	rows, err := q.db.Query(ctx, getAllJoinRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClubJoinRequest{}
	for rows.Next() {
		var i ClubJoinRequest
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.UserID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJoinRequestById = `-- name: GetJoinRequestById :one
SELECT id, club_id, user_id, status, created_at, updated_at, is_deleted
FROM club_join_requests
WHERE
    id = $1 and
    is_deleted = false
LIMIT 1
`

func (q *Queries) GetJoinRequestById(ctx context.Context, id int64) (ClubJoinRequest, error) {
	row := q.db.QueryRow(ctx, getJoinRequestById, id)
	var i ClubJoinRequest
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getJoinRequestsByClub = `-- name: GetJoinRequestsByClub :many
SELECT id, club_id, user_id, status, created_at, updated_at, is_deleted
FROM club_join_requests
WHERE
    club_id = $1 and
    is_deleted = false
`

func (q *Queries) GetJoinRequestsByClub(ctx context.Context, clubID int64) ([]ClubJoinRequest, error) {
	rows, err := q.db.Query(ctx, getJoinRequestsByClub, clubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClubJoinRequest{}
	for rows.Next() {
		var i ClubJoinRequest
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.UserID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
