// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clubs.sql

package db_queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllClubs = `-- name: GetAllClubs :many
SELECT
    clubs.id,
    clubs.name,
    clubs.description,
    clubs.sport_type_id,
    clubs.teacher_id,
    clubs.total_places,
    clubs.place,
    clubs.education_level_id,
    clubs.required_workout_per_week,
    clubs.created_at,
    clubs.updated_at,
    clubs.is_deleted,
    sport_types.name as sport_type_name,
    education_levels.name as education_level_name,
    users.full_name as teacher_name
FROM clubs
         LEFT JOIN sport_types ON clubs.sport_type_id = sport_types.id AND sport_types.is_deleted = false
         LEFT JOIN education_levels ON clubs.education_level_id = education_levels.id AND education_levels.is_deleted = false
         LEFT JOIN users ON clubs.teacher_id = users.id AND users.is_deleted = false
WHERE clubs.is_deleted = false
`

type GetAllClubsRow struct {
	ID                     int64
	Name                   string
	Description            string
	SportTypeID            int64
	TeacherID              int64
	TotalPlaces            *int32
	Place                  string
	EducationLevelID       int64
	RequiredWorkoutPerWeek int32
	CreatedAt              pgtype.Timestamp
	UpdatedAt              pgtype.Timestamp
	IsDeleted              bool
	SportTypeName          *string
	EducationLevelName     *string
	TeacherName            *string
}

func (q *Queries) GetAllClubs(ctx context.Context) ([]GetAllClubsRow, error) {
	rows, err := q.db.Query(ctx, getAllClubs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllClubsRow{}
	for rows.Next() {
		var i GetAllClubsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SportTypeID,
			&i.TeacherID,
			&i.TotalPlaces,
			&i.Place,
			&i.EducationLevelID,
			&i.RequiredWorkoutPerWeek,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
			&i.SportTypeName,
			&i.EducationLevelName,
			&i.TeacherName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClubById = `-- name: GetClubById :one
SELECT
    clubs.id,
    clubs.name,
    clubs.description,
    clubs.sport_type_id,
    clubs.teacher_id,
    clubs.total_places,
    clubs.place,
    clubs.education_level_id,
    clubs.required_workout_per_week,
    clubs.created_at,
    clubs.updated_at,
    clubs.is_deleted,
    sport_types.name as sport_type_name,
    education_levels.name as education_level_name,
    users.full_name as teacher_name
FROM clubs
         LEFT JOIN sport_types ON clubs.sport_type_id = sport_types.id AND sport_types.is_deleted = false
         LEFT JOIN education_levels ON clubs.education_level_id = education_levels.id AND education_levels.is_deleted = false
         LEFT JOIN users ON clubs.teacher_id = users.id AND users.is_deleted = false
WHERE clubs.id = $1 AND clubs.is_deleted = false
`

type GetClubByIdRow struct {
	ID                     int64
	Name                   string
	Description            string
	SportTypeID            int64
	TeacherID              int64
	TotalPlaces            *int32
	Place                  string
	EducationLevelID       int64
	RequiredWorkoutPerWeek int32
	CreatedAt              pgtype.Timestamp
	UpdatedAt              pgtype.Timestamp
	IsDeleted              bool
	SportTypeName          *string
	EducationLevelName     *string
	TeacherName            *string
}

func (q *Queries) GetClubById(ctx context.Context, id int64) (GetClubByIdRow, error) {
	row := q.db.QueryRow(ctx, getClubById, id)
	var i GetClubByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SportTypeID,
		&i.TeacherID,
		&i.TotalPlaces,
		&i.Place,
		&i.EducationLevelID,
		&i.RequiredWorkoutPerWeek,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.SportTypeName,
		&i.EducationLevelName,
		&i.TeacherName,
	)
	return i, err
}

const updateClub = `-- name: UpdateClub :one
UPDATE clubs
SET
    name = $2,
    description = $3,
    sport_type_id = $4,
    teacher_id = $5,
    total_places = $6,
    place = $7,
    education_level_id = $8,
    required_workout_per_week = $9,
    updated_at = now()
WHERE id = $1 AND is_deleted = false
RETURNING id, name, description, sport_type_id, teacher_id, total_places, place, education_level_id, required_workout_per_week, created_at, updated_at, is_deleted
`

type UpdateClubParams struct {
	ID                     int64
	Name                   string
	Description            string
	SportTypeID            int64
	TeacherID              int64
	TotalPlaces            *int32
	Place                  string
	EducationLevelID       int64
	RequiredWorkoutPerWeek int32
}

func (q *Queries) UpdateClub(ctx context.Context, arg UpdateClubParams) (Club, error) {
	row := q.db.QueryRow(ctx, updateClub,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.SportTypeID,
		arg.TeacherID,
		arg.TotalPlaces,
		arg.Place,
		arg.EducationLevelID,
		arg.RequiredWorkoutPerWeek,
	)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SportTypeID,
		&i.TeacherID,
		&i.TotalPlaces,
		&i.Place,
		&i.EducationLevelID,
		&i.RequiredWorkoutPerWeek,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}
