// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db_queries

import (
	"time"
)

type Group struct {
	ID             int64
	Institute      string
	EnrollmentYear int32
	Prefix         *string
	GroupTypeID    int64
	GroupNumber    *int16
	CreatedAt      time.Time
	UpdatedAt      time.Time
	IsDeleted      bool
}

type GroupType struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	IsDeleted bool
}

type User struct {
	ID                int64
	FullName          string
	SocialNetworkLink string
	PhoneNumber       string
	Email             string
	BirthDate         time.Time
	Role              string
	Password          []byte
	GroupID           *int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
	IsDeleted         bool
}
