// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db_queries

import (
	"context"
)

type Querier interface {
	CheckWorkoutExists(ctx context.Context, id int64) (bool, error)
	CheckClubExists(ctx context.Context, id int64) (bool, error)
	CheckClubOwnership(ctx context.Context, arg CheckClubOwnershipParams) (bool, error)
	CheckEducationLevelExistsByName(ctx context.Context, name string) (bool, error)
	CheckSportTypeExists(ctx context.Context, id int64) (bool, error)
	CreateClub(ctx context.Context, arg CreateClubParams) (Club, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetClubByID(ctx context.Context, id int64) (Club, error)
	GetClubsByTeacher(ctx context.Context, teacherID int64) ([]Club, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserById(ctx context.Context, id int64) (GetUserByIdRow, error)
	GetWorkoutsByClub(ctx context.Context, clubID int64) ([]GetWorkoutsByClubRow, error)
	SoftDeleteWorkout(ctx context.Context, id int64) error
	ListActiveClubs(ctx context.Context) ([]Club, error)
	SoftDeleteClub(ctx context.Context, id int64) error
}

var _ Querier = (*Queries)(nil)
