// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db_queries

import (
	"context"
)

type Querier interface {
	CreateJoinRequest(ctx context.Context, arg CreateJoinRequestParams) (ClubJoinRequest, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetJoinRequests(ctx context.Context, arg GetJoinRequestsParams) ([]ClubJoinRequest, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserById(ctx context.Context, id int64) (GetUserByIdRow, error)
}

var _ Querier = (*Queries)(nil)
