// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workouts.sql

package db_queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkWorkoutExists = `-- name: CheckWorkoutExists :one
SELECT EXISTS(
    SELECT 1 FROM workouts
    WHERE id = $1 AND is_deleted = FALSE
)
`

func (q *Queries) CheckWorkoutExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, checkWorkoutExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getWorkoutsByClub = `-- name: GetWorkoutsByClub :many
SELECT id, club_id, start_date, end_date, cancelled, created_at, updated_at
FROM workouts
WHERE club_id = $1 AND is_deleted = FALSE AND cancelled = FALSE
ORDER BY start_date DESC
`

type GetWorkoutsByClubRow struct {
	ID        int64
	ClubID    int64
	StartDate pgtype.Timestamp
	EndDate   pgtype.Timestamp
	Cancelled bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) GetWorkoutsByClub(ctx context.Context, clubID int64) ([]GetWorkoutsByClubRow, error) {
	rows, err := q.db.Query(ctx, getWorkoutsByClub, clubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWorkoutsByClubRow{}
	for rows.Next() {
		var i GetWorkoutsByClubRow
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.StartDate,
			&i.EndDate,
			&i.Cancelled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteWorkout = `-- name: SoftDeleteWorkout :exec
UPDATE workouts
SET is_deleted = TRUE, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteWorkout(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteWorkout, id)
	return err
}
