// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workouts.sql

package db_queries

import (
	"context"
	"time"
)

const createWorkout = `-- name: CreateWorkout :one
INSERT INTO workouts
(club_id, start_date, end_date)
VALUES
($1, $2, $3)
RETURNING workouts.id, workouts.club_id, workouts.start_date, workouts.end_date, workouts.cancelled, workouts.created_at, workouts.updated_at, workouts.is_deleted
`

type CreateWorkoutParams struct {
	ClubID    int64
	StartDate time.Time
	EndDate   time.Time
}

func (q *Queries) CreateWorkout(ctx context.Context, arg CreateWorkoutParams) (Workout, error) {
	row := q.db.QueryRow(ctx, createWorkout, arg.ClubID, arg.StartDate, arg.EndDate)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.StartDate,
		&i.EndDate,
		&i.Cancelled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}
